export const pricingPlans = [
  {
    id: 'analyse' as const,
    headline: 'Analyse',
    price: '£29',
    cadence: '/month',
    description: 'Turn Reddit threads, YouTube comments, reviews and forum conversations into executive ready Community Intelligence Briefs in minutes.',
    features: [
      'Manual conversation analysis',
      'Community Intelligence Score',
      'Executive Summary',
      'Pain Points',
      'Buying Intent',
      'Competitor Mentions',
      'AI Search Opportunities',
      'Recommended Actions',
      'Generate Community Intelligence Brief',
    ],
    cta: 'Launch Analyse',
    href: '#clerk-billing',
    status: 'active',
  },
  {
    id: 'discover' as const,
    headline: 'Discover',
    price: '£99',
    cadence: '/month',
    badge: 'Best for growing teams',
    recommended: true,
    description: 'Discover high value community conversations about your brand, competitors and category before your competitors do.',
    features: [
      'Everything in Analyse',
      'Brand and competitor discovery',
      'Platform search setup',
      'Search depth and timeframe options',
      'Opportunity ranking',
      'Competitor intelligence',
      'Content roadmap',
      'AI Search opportunities',
      'Executive Community Intelligence Brief',
    ],
    cta: 'Launch Discover',
    href: '#clerk-billing',
    status: 'active',
  },
  {
    id: 'alerts' as const,
    headline: 'Alerts',
    price: 'Waitlist',
    badge: 'Coming Soon',
    description: 'Receive executive Community Intelligence Alerts automatically as your market changes.',
    features: [
      'Continuous community monitoring',
      'Competitor activity alerts',
      'Reputation risk alerts',
      'Buying intent alerts',
      'AI Search opportunity alerts',
      'Scheduled intelligence briefings',
      'Community Pulse',
      'Executive alert preview',
    ],
    cta: 'Join Alerts Waitlist',
    href: '/app/alerts',
    status: 'coming-soon',
  },
];

export const pricingValueStatements = [
  'Executive ready Community Intelligence Briefs',
  'AI powered analysis using The Redditrepreneur Framework',
  'Replace hours of manual research in minutes',
];
