export const pricingPlans = [
  {
    id: 'analyse' as const,
    headline: 'Analyse',
    price: '\u00a329',
    cadence: '/month',
    description: 'Turn Reddit threads, YouTube comments, reviews and forum conversations into executive ready Community Intelligence Assessments in minutes.',
    features: [
      'Manual conversation analysis',
      'Community Intelligence Score',
      'Executive Summary',
      'Pain Points',
      'Buying Intent',
      'Competitor Mentions',
      'AI Search Opportunities',
      'Recommended Actions',
      'Generate Community Intelligence Assessment',
    ],
    cta: 'Launch Analyse',
    href: '#',
    status: 'active',
  },
  {
    id: 'discover' as const,
    headline: 'Discover',
    price: '\u00a399',
    cadence: '/month',
    badge: 'Reddit first discovery',
    recommended: true,
    description: 'Search supported Reddit public results for conversations about your brand, competitors and category, then turn them into a Community Intelligence Assessment.',
    features: [
      'Everything in Analyse',
      'Brand and competitor discovery',
      'Platform search setup',
      'Search depth and timeframe options',
      'Opportunity ranking',
      'Competitor intelligence',
      'Content roadmap',
      'AI Search opportunities',
      'Executive Community Intelligence Assessment',
    ],
    cta: 'Launch Discover',
    href: '#',
    status: 'active',
  },
  {
    id: 'alerts' as const,
    headline: 'Community Intelligence Alerts',
    price: '\u00a3249',
    cadence: '/month',
    badge: 'Best for ongoing intelligence',
    description: 'Monitor meaningful changes in public community conversations and know what to do next.',
    features: [
      'Up to 10 active or paused Alert Monitors',
      'Reddit monitoring',
      'Daily, weekly or monthly scans',
      'Community Health tracking',
      'Buying intent and competitor movement',
      'Sentiment and customer question monitoring',
      'Dashboard and email alert history',
      'Executive recommended actions',
    ],
    cta: 'Start Alerts',
    href: '#',
    status: 'active',
  },
];
