'use client';
import { useState } from 'react';
import { CheckoutButton } from '@/components/pricing/CheckoutButton';
import { Button } from '@/components/ui/Button';

export function AlertsUpgrade(){return <section className="alerts-upgrade"><div><div className="eyebrow">Community Intelligence Alerts</div><h1>Stay ahead of meaningful community change</h1><p>Monitor important changes in public conversations about your brand, market and competitors, then understand what changed, why it matters and what to do next.</p><div className="price">£249 <span>/month</span></div><p className="helper">Billed monthly. Cancel at any time.</p><CheckoutButton plan="alerts">Activate Alerts</CheckoutButton><Button href="/app/dashboard" variant="secondary">Return to Dashboard</Button></div><ul>{['Up to 10 Alert Monitors','Reddit monitoring','Daily, weekly or monthly scans','Dashboard and email delivery','Community Health movement','Buying intent monitoring','Competitor movement monitoring','Recommended actions'].map(x=><li key={x}>{x}</li>)}</ul></section>}

export function AlertsWorkspace({checkoutSuccess=false}:{checkoutSuccess?:boolean}){
 const[showSetup,setShowSetup]=useState(false),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 async function createMonitor(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setNotice('');const data=new FormData(event.currentTarget);const response=await fetch('/api/alerts/monitors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(data))});const body=await response.json();setNotice(response.ok?'Alert Monitor created. Its first approved-source run will establish the baseline.':body.error||'Unable to create monitor.');setSaving(false)}
 return <>{checkoutSuccess?<section className="launch-state active"><strong>Community Intelligence Alerts is active</strong><span>Create your first Alert Monitor to establish a baseline and begin tracking meaningful changes.</span></section>:null}<section className="hero"><div className="eyebrow">Community Intelligence Alerts</div><div className="question">What changed, why does it matter, and what should you do next?</div><h1>Monitor what matters.</h1><p>Reddit is the first supported source. Additional community sources will be added without changing your Alert Monitors.</p></section><section className="status-panel"><div className="monitoring"><div><div className="status-pill"><span className="dot"/>Alerts active</div><h2>Your Alert Monitors</h2><p>Create a monitor to establish a baseline. Alerts are generated only when meaningful change is detected.</p></div><div className="next-brief"><span>Plan limit</span><strong>Up to 10<br/>monitors</strong></div></div><div className="signal-grid"><div className="signal"><h3>Source</h3><p>Reddit monitoring</p></div><div className="signal"><h3>Schedules</h3><p>Daily, weekly or monthly</p></div><div className="signal"><h3>Delivery</h3><p>Dashboard and email</p></div><div className="signal"><h3>Other sources</h3><p>Coming soon</p></div></div></section><section className="launch-card"><div><div className="eyebrow">Alert Monitors</div><h2>Establish your Community Intelligence baseline</h2><p>Choose the competitors, signals and schedule that matter to your business.</p></div><Button variant="orange" onClick={()=>setShowSetup(true)}>Create Alert Monitor</Button></section>{showSetup?<form className="setup-card" onSubmit={createMonitor}><h2>Create Alert Monitor</h2><div className="field-grid"><label>Monitor name<input name="name" required minLength={2} maxLength={100} placeholder="Brand and competitor movement"/></label><label>Frequency<select name="frequency"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label className="full">Competitors<input name="competitors" placeholder="Competitor names, separated by commas"/></label><label className="full">Keywords<input name="keywords" placeholder="Pricing, onboarding, alternatives"/></label><label className="full">Signals<input name="signalTypes" placeholder="Buying intent, sentiment, complaints, feature requests"/></label></div><Button variant="orange" type="submit" disabled={saving}>{saving?'Creating monitor...':'Create Monitor'}</Button>{notice?<p role="status" className="helper">{notice}</p>:null}</form>:null}</>
}
